openapi: 3.0.0
info:
  title: KIWI - API REST v1
  description: ''
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:3333
paths:
  /session:
    post:
      tags:
      - Session
      summary: Company authentication
      description: ''
      operationId: createSession
      parameters: []
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              required:
              - email
              - password
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: company@gmail.com
              password:  "1234"
      responses:
        200:
          description: 'Success'
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  company:
                    type: object
                    properties:
                      id: 
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        default:
          description: 'Error'
  /company:
    post:
      tags:
      - Company
      summary: Create
      description: ''
      operationId: createCompany
      parameters: []
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              required:
              - name
              - email
              - password
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
            example:
              name: company
              email: company@gmail.com
              password: "1234"
      responses:
        200:
          $ref: '#/components/responses/companyResponse'
        default:
          description: 'Error'
    put:
      tags:
      - Company
      summary: Update
      description: ''
      operationId: updateCompany
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              required:
              - id
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                email:
                  type: string
                oldPassword:
                  type: string
                password:
                  type: string
                  description: obrigatório caso preencha o campo `oldPassword`
                confirmPassword:
                  type: string
                  description: obrigatório caso preencha o campo `oldPassword`
            example:
              id: 1
              name: company
              email: company@gmail.com
              oldPassword: "1234"
              password: "4321"
              confirmPassword: "4321"
        required: true
      responses:
        200:
          $ref: '#/components/responses/companyResponse'
        default:
          description: 'Error'
components:
  responses:
    companyResponse:
      description: ''
      headers: {}
      content:
        application/json:
          schema:
            type: object
            properties:
              id: 
                type: integer
              name:
                type: string
              email:
                type: string
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
- httpBearer: []
tags:
- name: Session
  description: ''
- name: Company
  description: ''
